### ISSUE TITLE
argument order for bspatch

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaIO/BSDiff.jl#5]
Currently the `bspatch` function takes its arguments in this order:
```jl
bspatch(old, patch, [new])
``` 
This is because the `new` argument is the optional one: if you don't provide it, the output is written to a temporary file whose path is returned by `bspatch`. However, this differs from the `bspatch` command-line tool, which takes arguments in the same order as `bsdiff` (both function and command), namely in this order:
```sh
[bspatch|bsdiff] old new patch
```
As a function with an optional last argument, the order `old`, `patch`, `new` makes more sense, but it may be confusing for the function API to be different from the command line tool. Any opinions on what to do here? cc @staticfloat

**Comment by staticfloat** [comment]
I think we should just have two methods:

```julia
function bspatch(old, patch)
	new = ...
	bspatch(old, new, patch)
	return new
end

function bspatch(old, new, patch)
	...
end
```

Yes, it's a little weird that the `new` argument gets spliced in there, but there's not _that_ intuitive of an ordering here either, so might as well just stay consistent, IMO.

**Comment by StefanKarpinski** [comment]
Yeah, that's an option (oh multiple dispatch, you beautiful, flexible bastard). I'll change it to that 👍
